name: Testes e CI/CD

on: [push, pull_request]

jobs:
  teste:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0  # substitua por sua versão de Python

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # substitua pelo nome do seu arquivo de requisitos

    - name: Rodar Testes
      run: python -m unittest discover
